### ISSUE TITLE
[CameraCaptureUI] Fails on Android with path related exception

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/Uno.Samples#281] opened 2022-12-22 14:22 UTC
Testing Android throws exception when attempting to capture photo:
at System.Uri.get_LocalPath()
at Windows.Media.Capture.CameraCaptureUI.CaptureFile(CancellationToken ct, CameraCaptureUIMode mode) in C:\a\1\s\src\Uno.UWP\Media\Capture\CameraCaptureUI.Android.cs:line 56
at Windows.Foundation.AsyncOperation1.<BuildTaskAsync>d__5[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\a\1\s\src\Uno.Foundation\AsyncOperation.TResult.cs:line 47 at System.WindowsRuntimeSystemExtensions.<AsTaskCore>d__111[[Windows.Storage.StorageFile, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\a\1\s\src\Uno.UWP\System.Runtime\WindowsRuntimeSystemExtensions.cs:line 66
at CameraCaptureUISample.MainPage.button_Click(Object sender, RoutedEventArgs e) in C:\source\github\unoplatform\Uno.Samples\UI\CameraCaptureUI\CameraCaptureUISample\CameraCaptureUISample.Shared\MainPage.xaml.cs:line 41

**Comment by Youssef1313** [comment] 2023-02-20 20:59
Duplicate of https://github.com/unoplatform/uno/issues/9397

**Closed by Youssef1313** 2023-02-20 20:59 UTC
